### ISSUE TITLE
Software packages in SSH

### ISSUE THREAD

**Issue by michela12345** [lfam/guix#1]
I am using an ssh account that connects to an external server, i have downloaded through guix some software like samtools and bedtools but when i try to use them in my directory it gives me this error:

`-bash: samtools: command not found`

In my direcory, however, there is the directry guix.profile and if I go into the bin folder of this, I have everything I downloaded and if I run: 

`./samtools`

In that direcory, I can see it and works. But how I can use that software packages in another folder? I try with:

`PATH=$PATH:~/home/hub_galli/mfrancesconi/.guix-profile/bin 
export PATH `

But it doesn't work. What I'm doing wrong?

**Comment by lfam** [comment]
This repo is a personal development mirror of the Guix source code. No support is available here.

You can file bugs or get help on IRC:
https://guix.gnu.org/manual/en/html_node/The-Issue-Tracker.html
https://guix.gnu.org/en/contact/irc/
